import { create } from 'zustand';

export type Moment={id:string;title:string;time:string;context:string;people:number;duration:string;palette:string;saved:boolean;signalled:boolean;expires:string};
export type Nearby={id:string;name:string;tag:string;distance:string;color:string;initials:string;trust:number;signalSent?:boolean};
export type Match={id:string;name:string;initials:string;color:string;subtitle:string;unread:number;revealed:boolean;messages:{from:'them'|'me';text:string}[]};
const momentSeed:Moment[]=[{id:'m1',title:'Caffè lento',time:'Oggi · 18:42',context:'Bar Magenta · Brera',people:4,duration:'18 min insieme',palette:'#E5DEFF',saved:false,signalled:false,expires:'Scade tra 22h'},{id:'m2',title:'Ritorno a casa',time:'Oggi · 17:10',context:'Tram 3 · Porta Genova',people:2,duration:'11 min insieme',palette:'#D9F4EF',saved:true,signalled:false,expires:'Scade tra 20h'},{id:'m3',title:'Un tavolo vicino',time:'Ieri · 21:08',context:'Bicocca Village',people:6,duration:'46 min insieme',palette:'#FFE8CB',saved:false,signalled:true,expires:'Scade tra 3h'}];
const nearbySeed:Nearby[]=[{id:'n1',name:'Marta',tag:'Architettura',distance:'2 m',color:'#F7B7C8',initials:'M',trust:98},{id:'n2',name:'Leo',tag:'Design & musica',distance:'6 m',color:'#B9D9FF',initials:'L',trust:96},{id:'n3',name:'Sara',tag:'Startup',distance:'11 m',color:'#D9C6FF',initials:'S',trust:99},{id:'n4',name:'Nico',tag:'Cinema',distance:'16 m',color:'#BFE9D4',initials:'N',trust:94}];
const matchSeed:Match[]=[{id:'marta',name:'Marta',initials:'M',color:'#F7B7C8',subtitle:'Match reciproco · Bar Magenta',unread:1,revealed:false,messages:[{from:'them',text:'Ciao! Anche tu eri al tavolino con il libro blu?'}]},{id:'leo',name:'Leo',initials:'L',color:'#B9D9FF',subtitle:'Match reciproco · Tram 3',unread:0,revealed:true,messages:[{from:'them',text:'Mi è piaciuto il tuo segnale. Caffè uno di questi giorni?'}]}];
type State={live:boolean;invisible:boolean;moments:Moment[];nearby:Nearby[];matches:Match[];activeMatchId:string|null;setLive:(v:boolean)=>void;setInvisible:(v:boolean)=>void;toggleSaved:(id:string)=>void;sendMomentSignal:(id:string)=>void;sendLiveSignal:(id:string)=>void;openMatch:(id:string)=>void;sendMessage:(text:string)=>void;reveal:(id:string)=>void};
export const useRefind=create<State>((set)=>({live:true,invisible:false,moments:momentSeed,nearby:nearbySeed,matches:matchSeed,activeMatchId:null,setLive:(live)=>set({live}),setInvisible:(invisible)=>set({invisible,live:!invisible}),toggleSaved:(id)=>set(s=>({moments:s.moments.map(x=>x.id===id?{...x,saved:!x.saved}:x)})),sendMomentSignal:(id)=>set(s=>({moments:s.moments.map(x=>x.id===id?{...x,signalled:true}:x)})),sendLiveSignal:(id)=>set(s=>({nearby:s.nearby.map(x=>x.id===id?{...x,signalSent:true}:x)})),openMatch:(id)=>set(s=>({activeMatchId:id,matches:s.matches.map(x=>x.id===id?{...x,unread:0}:x)})),sendMessage:(text)=>set(s=>({matches:s.matches.map(x=>x.id===s.activeMatchId?{...x,messages:[...x.messages,{from:'me',text}]}:x)})),reveal:(id)=>set(s=>({matches:s.matches.map(x=>x.id===id?{...x,revealed:true}:x)}))}));
