import { FontAwesome6 } from '@expo/vector-icons';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRefind } from '../../src/useRefind';

const Row = ({ icon, title, subtitle, onPress }: { icon: React.ComponentProps<typeof FontAwesome6>['name']; title: string; subtitle: string; onPress?: () => void }) => <Pressable onPress={onPress} style={styles.row}><View style={styles.rowIcon}><FontAwesome6 name={icon} size={16} color="#4938E8" /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSub}>{subtitle}</Text></View><FontAwesome6 name="chevron-right" size={12} color="#AAA9B8" /></Pressable>;

export default function ProfileScreen() {
  const { invisible, setInvisible, moments } = useRefind();
  const saved = moments.filter((moment) => moment.saved).length;
  return <SafeAreaView style={styles.screen} edges={['top']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.kicker}>IL TUO SPAZIO</Text><Text style={styles.heading}>Profilo & privacy</Text>
    <View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>MC</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>Marco</Text><Text style={styles.handle}>@marco · Disponibile per un caffè</Text><View style={styles.tags}><Text style={styles.tag}>Design</Text><Text style={styles.tag}>Milano</Text></View></View><Pressable onPress={() => Alert.alert('Profilo', 'In una versione con backend qui potrai modificare alias, bio e interessi.')}><FontAwesome6 name="pen" size={15} color="#4938E8" /></Pressable></View>
    <View style={styles.stats}><View style={styles.stat}><Text style={styles.statNumber}>12</Text><Text style={styles.statLabel}>Echi questo mese</Text></View><View style={styles.line} /><View style={styles.stat}><Text style={styles.statNumber}>{saved}</Text><Text style={styles.statLabel}>Momenti salvati</Text></View><View style={styles.line} /><View style={styles.stat}><Text style={styles.statNumber}>2</Text><Text style={styles.statLabel}>Match reciproci</Text></View></View>
    <Text style={styles.section}>PRIVACY PRIMA DI TUTTO</Text>
    <View style={styles.visibility}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>Modalità invisibile</Text><Text style={styles.rowSub}>Non compari nel Live e non raccogli nuovi echi.</Text></View><Switch value={invisible} onValueChange={setInvisible} trackColor={{ false: '#DEDCE7', true: '#AFA8FF' }} thumbColor={invisible ? '#4938E8' : '#FFF'} /></View>
    <Text style={styles.section}>IL TUO REFIND</Text>
    <View style={styles.list}><Row icon="heart" title="I miei momenti" subtitle={`${saved} salvati · scadenza automatica attiva`} onPress={() => Alert.alert('I miei momenti', 'Gli echi non salvati vengono rimossi automaticamente dopo 24 ore.')} /><View style={styles.divider} /><Row icon="comments" title="Match e chat" subtitle="2 conversazioni reciproche" onPress={() => Alert.alert('Match', 'La chat si apre solo dopo un consenso reciproco.')} /><View style={styles.divider} /><Row icon="bell" title="Notifiche serali" subtitle="Digest attivo alle 20:30" onPress={() => Alert.alert('Notifiche', 'Le notifiche push richiedono il collegamento a un backend.')} /></View>
    <View style={styles.footer}><FontAwesome6 name="lock" size={13} color="#6C678E" /><Text style={styles.footerText}>I tuoi dati di prossimità sono effimeri. Non vendiamo né mostriamo la tua posizione.</Text></View>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F7FB' }, content: { padding: 20, paddingBottom: 30 }, kicker: { color: '#858598', fontSize: 10, fontWeight: '800', letterSpacing: 1.3, marginTop: 6 }, heading: { color: '#21212E', fontSize: 31, fontWeight: '800', letterSpacing: -1.3, marginTop: 4, marginBottom: 22 }, profile: { backgroundColor: '#FFF', borderRadius: 25, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14 }, avatar: { height: 64, width: 64, borderRadius: 22, backgroundColor: '#DCD8FF', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#4938E8', fontWeight: '900', fontSize: 20 }, name: { color: '#2A2A3A', fontWeight: '800', fontSize: 20 }, handle: { color: '#848394', fontSize: 11, marginTop: 3 }, tags: { flexDirection: 'row', gap: 5, marginTop: 9 }, tag: { backgroundColor: '#F0EEFF', color: '#5D5893', paddingHorizontal: 8, paddingVertical: 3, fontSize: 10, fontWeight: '700', borderRadius: 8 }, stats: { backgroundColor: '#4938E8', borderRadius: 24, paddingVertical: 18, marginTop: 14, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' }, stat: { flex: 1, alignItems: 'center' }, statNumber: { color: '#FFF', fontSize: 23, fontWeight: '900' }, statLabel: { color: '#CBC7FF', textAlign: 'center', fontSize: 9, fontWeight: '700', marginTop: 3, lineHeight: 12 }, line: { width: 1, height: 34, backgroundColor: '#7166F3' }, section: { color: '#69697B', fontWeight: '800', fontSize: 10, letterSpacing: 1.2, marginTop: 27, marginBottom: 10 }, visibility: { backgroundColor: '#FFF', borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center' }, rowTitle: { color: '#2B2B3B', fontSize: 14, fontWeight: '800' }, rowSub: { color: '#888799', fontSize: 11, marginTop: 3, lineHeight: 16 }, list: { backgroundColor: '#FFF', borderRadius: 20, overflow: 'hidden' }, row: { padding: 16, flexDirection: 'row', gap: 12, alignItems: 'center' }, rowIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: '#F0EEFF', alignItems: 'center', justifyContent: 'center' }, divider: { height: 1, backgroundColor: '#F0EFF5', marginLeft: 64 }, footer: { backgroundColor: '#EFEEFF', padding: 15, borderRadius: 17, marginTop: 18, flexDirection: 'row', gap: 10 }, footerText: { flex: 1, color: '#6C678E', fontWeight: '600', fontSize: 11, lineHeight: 16 } });
